version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_APP_API_BASE_URL: ${VITE_APP_API_BASE_URL}
        VITE_APP_BASE_URL: ${VITE_APP_BASE_URL}
        VITE_APP_IMP_KEY: ${VITE_APP_IMP_KEY}
    ports:
      - "80:80"
    environment:
      VITE_APP_API_BASE_URL: ${VITE_APP_API_BASE_URL}
      VITE_APP_BASE_URL: ${VITE_APP_BASE_URL}
      VITE_APP_IMP_KEY: ${VITE_APP_IMP_KEY}
    depends_on:
      - backend
    networks:
      - linguagen-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8085:8085"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - linguagen-network

networks:
  linguagen-network:
