services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8085:8085' # Spring Boot 기본 포트
    networks:
      - linguagen-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173' # React 기본 포트
    networks:
      - linguagen-net

networks:
  linguagen-net:
